### ISSUE TITLE
Add a configurable background job that can be added to archive old resolved application errors

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/dropwizard-application-errors#105]

**Comment by sleberknight** [comment]
We could also have separate expiration thresholds for resolved vs. unresolved. For example 2 weeks for resolved errors, but 2 months for unresolved. Etc.

**Comment by chrisrohr** [comment]
@sleberknight I didn't see your last comment before I submitted the PR.  Let me know if you want me to add the extra config value for resolved versus unresolved and I will add it.
