### ISSUE TITLE
Move ServiceDetails to model package?

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-application-errors#35]
Should we move `ServiceDetails` from the base package (`org.kiwiproject.dropwizard.error`) to the `<base-pkg>.model` package?

It's accessed by the `RecentErrorsHealthCheck` in the `<base-pkg>.health` package which creates a cyclic dependency between the base package and the health package. Putting it in `model` seems more appropriate anyway, and is at the same package "level", i.e. it is a "peer" instead of a child accessing its parent directly.

It will soon also be accessed by the (as of now unimplemented) `ErrorContext` and `ErrorContextBuilder` classes that bootstrap this library in a Dropwizard application.

Thoughts?

**Comment by chrisrohr** [comment]
I think that makes the most sense
