### ISSUE TITLE
Add ErrorContextBuilder

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-application-errors#38]
This class is a builder for `ErrorContext` instances.

This issue depends on completion of:

- #36 
- #37

**Comment by sleberknight** [comment]
Can the entry point be something like `ErrorContext.builder()` which would be a a `default` method in the interface and would return an instance of `ErrorContextBuilder`?

**Comment by sleberknight** [comment]
e.g. in `ErrorContext`:

```java
default ErrorContextBuilder builder() {
    return new ErrorContextBuilder();
}
```

**Comment by chrisrohr** [comment]
Because there is builder in the name, use the newInstance() version
